version: '2'
# 定义三个服务nginx,php,mysql
services:
  nginx:
    # 依赖php服务，意味着在启动nginx之前先启动php
    depends_on:
      - php
      # nginx镜像的路径
    build: ./nginx
        # 这样使nginx容器把网站文件和目录存放到主机目录中，持久化和方便管理
    volumes:
      - /docker/nginx/www:/usr/share/nginx/html
      - /docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /docker/nginx/log/error.log:/var/log/nginx/error.log
        # nginx意外退出时自动重启
    restart: always

        # 映射80和443端口
    ports:
      - "80:80"
      - "443:443"

        # 容器名称
    container_name: nginx
  php:
    build: ./php
    ports:
      - "9000"
    volumes:
      - ./php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
      - ./php/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
      - ./php/php.ini:/usr/local/php/etc/php.ini
      - ./php/log/php-fpm.log:/usr/local/php/var/log/php-fpm.log
      - ./nginx/www:/usr/share/nginx/html
    restart: always
    container_name: php
